some coding violations.  Hard tabs instead of soft expanded ones.
Also, it wasn't building for me due to some type mismatches and some
warnings.

Reminder to build with -Werror and -Wall.

plfsunit.cpp: In member function ‘void PlfsUnit::chmodTest()’:
plfsunit.cpp:168: error: no matching function for call to ‘assertEquals(mode_t&, int, CppUnit::SourceLine, const char [1])’
plfsunit.cpp: In member function ‘void PlfsUnit::chmodDirTest()’:
plfsunit.cpp:188: error: no matching function for call to ‘assertEquals(mode_t&, int, CppUnit::SourceLine, const char [1])’
cc1plus: warnings being treated as errors
plfsunit.cpp: In member function ‘void PlfsUnit::symlinkTest()’:
plfsunit.cpp:275: warning: comparison between signed and unsigned integer expressions
plfsunit.cpp: In member function ‘void PlfsUnit::renameTest()’:
plfsunit.cpp:313: warning: unused variable ‘fd’
make[2]: *** [plfsunit-plfsunit.o] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2



git-svn-id: https://plfs.svn.sourceforge.net/svnroot/plfs/trunk@872 979fb63a-54b4-4514-8d67-9ab8ea1b59df